### ISSUE TITLE
codegen: AttributeError: 'NullValueNode' object has no attribute 'value'

### ISSUE THREAD

**Issue by moorereason** [profusion/sgqlc#119]
While trying to generate a schema today, I received an error:

```
$ python --version
Python 3.9.1

$ pip list  | grep sgqlc
sgqlc             12.1

$ python -m sgqlc.introspection \
     --exclude-deprecated --exclude-description \
     -H "Authorization: bearer ${TOKEN}" \
     $API_URL \
     canvas_schema.py.json

$ sgqlc-codegen schema canvas_schema.py.json canvas_schema.py
Traceback (most recent call last):
  File "/src/canvas/venv/bin/sgqlc-codegen", line 8, in <module>
    sys.exit(main())
  File "/src/canvas/venv/lib/python3.9/site-packages/sgqlc/codegen/__init__.py", line 51, in main
    args.func(args)
  File "/src/canvas/venv/lib/python3.9/site-packages/sgqlc/codegen/schema.py", line 562, in handle_command
    gen.write()
  File "/src/canvas/venv/lib/python3.9/site-packages/sgqlc/codegen/schema.py", line 114, in write
    self.write_types()
  File "/src/canvas/venv/lib/python3.9/site-packages/sgqlc/codegen/schema.py", line 215, in write_types
    mapped(t)
  File "/src/canvas/venv/lib/python3.9/site-packages/sgqlc/codegen/schema.py", line 386, in write_type_object
    self.write_type_container(t, bases, own_fields, write_field)
  File "/src/canvas/venv/lib/python3.9/site-packages/sgqlc/codegen/schema.py", line 337, in write_type_container
    write_field(field, siblings)
  File "/src/canvas/venv/lib/python3.9/site-packages/sgqlc/codegen/schema.py", line 318, in write_field_output
    self.write_arg(a, siblings)
  File "/src/canvas/venv/lib/python3.9/site-packages/sgqlc/codegen/schema.py", line 292, in write_arg
    defval = repr(parse_graphql_value_to_json(defval))
  File "/src/canvas/venv/lib/python3.9/site-packages/sgqlc/codegen/schema.py", line 66, in parse_graphql_value_to_json
    v = v.value
AttributeError: 'NullValueNode' object has no attribute 'value'
```

The API in question is described at https://canvas.instructure.com/doc/api/file.graphql.html.  I'm assuming that I'm not at liberty to share the schema, but let me know how I can help troubleshoot.

**Comment by barbieri** [comment]
ah, I know this bug... JSONOutputVisitor returns `None` from `leave_NullValue` and that is understood as  'preserve the old value', which is the `NullValueNode`. It's not being replaced as it should. I'll fix that

**Comment by barbieri** [comment]
@moorereason take a look at `master`, see if 8ff6d9c5cf7129b141d2ea1ad0c2ea27e5627e27 fixes that.

**Comment by moorereason** [comment]
That fixed the issue.  Thanks 👍

**Comment by dupuy26** [comment]
This problem is also occurring with the GitHub GraphQL API (if you get it from the API endpoint). Any time frame for a 12.2 release that includes this fix?

**Comment by barbieri** [comment]
done https://pypi.org/project/sgqlc/12.2/

I was willing to do more work on it, but i couldn't. So I released this new version with bugfixes only.
