### ISSUE TITLE
Issues with generating operation with sgqlc-codegen

### ISSUE THREAD

**Issue by SuperSonicHub1** [profusion/sgqlc#125]
On running this command:
```
sgqlc-codegen operation --schema graphql/schema.json twitch_sgqlc:schema witch_api/operations/operations.py graphql/operations.graphql
```
with this GQL:
```graphql
query GetChannelInformation($ids: [ID!]) {
  users(ids: $ids) {
    broadcaster_id: id
    broadcaster_name: displayName
    broadcastSettings {
      ...broadcastSettingsChannelInfo
    }
  }
}

fragment broadcastSettingsChannelInfo on BroadcastSettings {
  broadcaster_id: language
  game {
    ...broadcastSettingsGameChannelInfo
  }
  title
}

fragment broadcastSettingsGameChannelInfo on Game {
  game_id: id
  game_name: name
}
```
I get a `graphql.pyutils.frozen_error.FrozenError`:
```
Traceback (most recent call last):
  File "/home/kyleanthonywilliams2/.cache/pypoetry/virtualenvs/witch-api-3UfxtcFu-py3.7/bin/sgqlc-codegen", line 8, in <module>
    sys.exit(main())
  File "/home/kyleanthonywilliams2/.cache/pypoetry/virtualenvs/witch-api-3UfxtcFu-py3.7/lib/python3.7/site-packages/sgqlc/codegen/__init__.py", line 51, in main
    args.func(args)
  File "/home/kyleanthonywilliams2/.cache/pypoetry/virtualenvs/witch-api-3UfxtcFu-py3.7/lib/python3.7/site-packages/sgqlc/codegen/operation.py", line 746, in handle_command
    gen.write()
  File "/home/kyleanthonywilliams2/.cache/pypoetry/virtualenvs/witch-api-3UfxtcFu-py3.7/lib/python3.7/site-packages/sgqlc/codegen/operation.py", line 628, in write
    self.write_operations()
  File "/home/kyleanthonywilliams2/.cache/pypoetry/virtualenvs/witch-api-3UfxtcFu-py3.7/lib/python3.7/site-packages/sgqlc/codegen/operation.py", line 645, in write_operations
    self.write_operation(source)
  File "/home/kyleanthonywilliams2/.cache/pypoetry/virtualenvs/witch-api-3UfxtcFu-py3.7/lib/python3.7/site-packages/sgqlc/codegen/operation.py", line 655, in write_operation
    for kind, name, code in visit(gql, visitor):
  File "/home/kyleanthonywilliams2/.cache/pypoetry/virtualenvs/witch-api-3UfxtcFu-py3.7/lib/python3.7/site-packages/graphql/language/visitor.py", line 314, in visit
    result = visit_fn(node, key, parent, path, ancestors)
  File "/home/kyleanthonywilliams2/.cache/pypoetry/virtualenvs/witch-api-3UfxtcFu-py3.7/lib/python3.7/site-packages/sgqlc/codegen/operation.py", line 475, in leave_field
    node.arguments.append(('__alias__', alias))
  File "/home/kyleanthonywilliams2/.cache/pypoetry/virtualenvs/witch-api-3UfxtcFu-py3.7/lib/python3.7/site-packages/graphql/pyutils/frozen_list.py", line 45, in append
    raise FrozenError
```
Help?

**Comment by barbieri** [comment]
Seems my code was broken with aliases. See if #126 fixes it

**Comment by SuperSonicHub1** [comment]
It works! Push it as soon as possible.

Kyle Williams


Kyle Williams

**Comment by SuperSonicHub1** [comment]
Wait, don't push yet, just realized something! For fragments, you don't get the types needed from the `schema-name` variable. For example, if `schema-name` is `twitch_sgqlc:schema`, types aren't imported from `twitch_schema.schema` but instead `twitch_schema`, which doesn't work!

Here's the code generated for context:
```python
import sgqlc.types
import sgqlc.operation
import twitch_schema

__all__ = ('Operations',)


def fragment_broadcast_settings_channel_info():
    _frag = sgqlc.operation.Fragment(twitch_schema.BroadcastSettings, 'broadcastSettingsChannelInfo')
    _frag.language(__alias__='broadcaster_language')
    _frag_game = _frag.game()
    _frag_game.__fragment__(fragment_broadcast_settings_game_channel_info())
    _frag.title()
    return _frag


def fragment_broadcast_settings_game_channel_info():
    _frag = sgqlc.operation.Fragment(twitch_schema.Game, 'broadcastSettingsGameChannelInfo')
    _frag.id(__alias__='game_id')
    _frag.name(__alias__='game_name')
    return _frag


class Fragment:
    broadcast_settings_channel_info = fragment_broadcast_settings_channel_info()
    broadcast_settings_game_channel_info = fragment_broadcast_settings_game_channel_info()


def query_get_channel_information():
    _op = sgqlc.operation.Operation(twitch_schema.schema.query_type, name='GetChannelInformation', variables=dict(ids=sgqlc.types.Arg(sgqlc.types.list_of(sgqlc.types.non_null(twitch_schema.schema.ID)))))
    _op_users = _op.users(ids=sgqlc.types.Variable('ids'))
    _op_users.id(__alias__='broadcaster_id')
    _op_users.display_name(__alias__='broadcaster_name')
    _op_users_broadcast_settings = _op_users.broadcast_settings()
    _op_users_broadcast_settings.__fragment__(fragment_broadcast_settings_channel_info())
    return _op


class Query:
    get_channel_information = query_get_channel_information()


class Operations:
    fragment = Fragment
    query = Query
```

**Comment by SuperSonicHub1** [comment]
Also, after fixing the imports, I'm now getting a strange `TypeError`. It seems to happen after you assign the `$ids` variable to `ids` in `_op.users` and then try to export the query as a string.
Here's the error I get:
```
Traceback (most recent call last):
  File "/home/kyleanthonywilliams2/.cache/pypoetry/virtualenvs/witch-api-3UfxtcFu-py3.7/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/kyleanthonywilliams2/Active/witch_api/witch_api/__init__.py", line 2, in <module>
    from .app import app
  File "/home/kyleanthonywilliams2/Active/witch_api/witch_api/app.py", line 2, in <module>
    from .helix import helix
  File "/home/kyleanthonywilliams2/Active/witch_api/witch_api/helix/__init__.py", line 1, in <module>
    from .helix import helix
  File "/home/kyleanthonywilliams2/Active/witch_api/witch_api/helix/helix.py", line 3, in <module>
    from ..operations import Operations
  File "/home/kyleanthonywilliams2/Active/witch_api/witch_api/operations/__init__.py", line 1, in <module>
    from .operations import Operations
  File "/home/kyleanthonywilliams2/Active/witch_api/witch_api/operations/operations.py", line 41, in <module>
    class Query:
  File "/home/kyleanthonywilliams2/Active/witch_api/witch_api/operations/operations.py", line 42, in Query
    get_channel_information = query_get_channel_information()
  File "/home/kyleanthonywilliams2/Active/witch_api/witch_api/operations/operations.py", line 33, in query_get_channel_information
    print(_op) # Second
  File "/home/kyleanthonywilliams2/.cache/pypoetry/virtualenvs/witch-api-3UfxtcFu-py3.7/lib/python3.7/site-packages/sgqlc/operation/__init__.py", line 2097, in __str__
    return self.__to_graphql__()
  File "/home/kyleanthonywilliams2/.cache/pypoetry/virtualenvs/witch-api-3UfxtcFu-py3.7/lib/python3.7/site-packages/sgqlc/operation/__init__.py", line 2068, in __to_graphql__
    indent, indent_string, auto_select_depth)
  File "/home/kyleanthonywilliams2/.cache/pypoetry/virtualenvs/witch-api-3UfxtcFu-py3.7/lib/python3.7/site-packages/sgqlc/operation/__init__.py", line 1725, in __to_graphql__
    next_indent, indent_string, auto_select_depth,
  File "/home/kyleanthonywilliams2/.cache/pypoetry/virtualenvs/witch-api-3UfxtcFu-py3.7/lib/python3.7/site-packages/sgqlc/operation/__init__.py", line 1421, in __to_graphql__
    self.__args__, indent, indent_string)
  File "/home/kyleanthonywilliams2/.cache/pypoetry/virtualenvs/witch-api-3UfxtcFu-py3.7/lib/python3.7/site-packages/sgqlc/types/__init__.py", line 2340, in __to_graphql_input__
    args.append(p.__to_graphql_input__(v))
  File "/home/kyleanthonywilliams2/.cache/pypoetry/virtualenvs/witch-api-3UfxtcFu-py3.7/lib/python3.7/site-packages/sgqlc/types/__init__.py", line 2182, in __to_graphql_input__
    v = self.type.__to_graphql_input__(value, indent, indent_string)
  File "/home/kyleanthonywilliams2/.cache/pypoetry/virtualenvs/witch-api-3UfxtcFu-py3.7/lib/python3.7/site-packages/sgqlc/types/__init__.py", line 977, in __to_graphql_input__
    for v in value:
TypeError: 'Variable' object is not iterable
```

**Comment by barbieri** [comment]
in your import case, if it's a schema file inside a `twitch_sgqlc` package, then it should be imported as `from twitch_sgqlc import schema`, at least that was my idea, but I didn't test and it may be wrong.

**Comment by barbieri** [comment]
and this list type needs a check, if there is a variable instead of an actual list of values

**Comment by barbieri** [comment]
@SuperSonicHub1 the new commit 3f99938354b3a6f9f33ea07792510dba28efade6 fixes the variable-as-list argument problem, thanks for finding it.

As for the schema, do you have a patch or the command line you're using to generate?

**Comment by barbieri** [comment]
> in your import case, if it's a schema file inside a `twitch_sgqlc` package, then it should be imported as `from twitch_sgqlc import schema`, at least that was my idea, but I didn't test and it may be wrong.

I was wrong, did a quick test and it generates `import twitch_sgqlc.schema`, but seems to use the correct symbol `twitch_sgqlc.schema` in the generated code.

**Comment by barbieri** [comment]
@SuperSonicHub1 I think the parameter documentation is not that good, but the code is correct:

if `schema-name` is `twitch_sgqlc:schema`, then it means the module is `twitch_sgqlc`, that's where the types are declared. The `schema` part (symbol) is just the raw entry point (usually the same name due `sgqlc-codegen` default). See Shopify example, it's `shopify_schema`, while GitHub's `github_schema`. We just use this symbol to get the `query_type`, `mutation_type` and `subscription_type`.

So if you want to use something different, in your case it would be `twitch_sgqlc.schema:schema`, that should `import twitch_sgqlc.schema` and then get the root types from `twitch_sgqlc.schema.schema`.

**Comment by barbieri** [comment]
sent a new commit to use top level names `_schema` and `_schema_root`, will make generated code cleaner, smaller and simpler to understand what's going on.

**Comment by SuperSonicHub1** [comment]
@barbieri Thanks for all the new patches! I'll make sure to test everything ASAP.

**Comment by SuperSonicHub1** [comment]
@barbieri Also, when do intend to push these changes to PyPI? Using Git for package installation can be quite finicky.

**Comment by SuperSonicHub1** [comment]
@barbieri The Variable issue has been fixed!

I tried the command you suggested (`sgqlc-codegen operation --schema graphql/schema.json twitch_sgqlc.schema:schema witch_api/operations/operations.py graphql/operations.graphql`), but now I'm getting an attribute error as `twitch_sgqlc.schema.schema` doesn't exist. It seems that there is some miscommunication on how I'm handling the import on my end. Luckily, my generated schema is on GitHub so that you can figure out what is going on ([supersonichub1/twitch_sgqlc](https://github.com/supersonichub1/twitch_sgqlc)), but here's my module's `__init__.py` in case you need the short version:
```python
__version__ = "0.1.0"
from .schema import schema
from .client_id import DEFAULT_CLIENT_ID, CLIENT_ID_REGEX, get_client_id
```

**Comment by barbieri** [comment]
@SuperSonicHub1 I'll release to PyPi as soon as you confirm everything works, it's pretty simple.

As for your code, it seems right: https://raw.githubusercontent.com/SuperSonicHub1/twitch_sgqlc/master/twitch_sgqlc/schema.py it's the module `twitch_sgqlc.schema` and inside it there is a `schema` object, created in this line

```py
schema = sgqlc.types.Schema()
```

This `from .schema import schema` shouldn't be needed, since the import would get you the `twitch_sgqlc/schema.py` file.

Where you're locating your operations file? maybe that's the issue? If you place it inside `twitch_sgqlc` you may use the `.schema` instead, then it should create a `from . import schema`

As for your client_id, never put it inside a repository. Usually that's something you ask people to pass to your app as command line argument or environment variable (see my examples how tokens are handled).

**Comment by SuperSonicHub1** [comment]
@barbieri Cool, it's just that other repo maintainers I work with take longer than I expect to integrate their changes.

I import the schema directly as I don't want to pollute my imports with a bunch of unrelated packages, but I do want my code to work so I'll just change my code to be something like `from . import schema`.

My operations file is in a separate project.

Don't worry about the Client-ID, `twitch_sgqlc` is a web-scraping project and the ID is publicly available in Twitch's HTML. ;)

**Comment by SuperSonicHub1** [comment]
@barbieri Sorry I took so long to respond, life got in the way of this little project of mine. After changing my import, `sgqlc-codegen` now works perfectly. Please, push the new branch as soon as you can!

**Comment by barbieri** [comment]
done already, see if the released code works properly and then close this ticket

**Comment by SuperSonicHub1** [comment]
@barbieri I installed sgqlc from the main branch and am now running into that same `FrozenError` you already patched. You sure you merged the branches?
