### ISSUE TITLE
sgqlc-codegen fails with an AttributeError

### ISSUE THREAD

**Issue by rveeravalli** [profusion/sgqlc#139]
Hi,

Firstly thank you for making this library. I have been using sgqlc for working with Canvas LMS for over a year and it has worked well.

After a schema update on my LMS, I pulled the latest JSON file, but noticed that sgqlc-codegen has stopped working and errors out while attempting to generate the python file. I am using the latest version of the library. I have attached the schema.json file and the command that I used to replicate the issue.  

`sgqlc-codegen schema canvas_schema.json canvas_schema.py`

I receive the following error message
`AttributeError: 'NullValueNode' object has no attribute 'value'`

I can't tell whether the issue is with my LMS or if it's a bug with sgqlc-codegen. Hence, I'm posting this as an issue. 

Any help would be most appreciated. Thank you.

[canvas_schema.zip](https://github.com/profusion/sgqlc/files/6194259/canvas_schema.zip)

**Comment by barbieri** [comment]
given the error, it's a bug in the sgqlc (even if the input is wrong, the code should behave).

I can't check it right now, but if you can share the fullbacktrace it will help me to think on the possible issues.

**Comment by rveeravalli** [comment]
Thank you. Please find the traceback below
`Traceback (most recent call last):
  File "C:\Users\rv\AppData\Local\Programs\Python\Python38-32\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\rv\AppData\Local\Programs\Python\Python38-32\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\rv\.virtualenvs\lms-proj\Scripts\sgqlc-codegen.exe\__main__.py", line 7, in <module>
  File "c:\users\rv\.virtualenvs\lms-proj\lib\site-packages\sgqlc\codegen\__init__.py", line 51, in main
    args.func(args)
  File "c:\users\rv\.virtualenvs\lms-proj\lib\site-packages\sgqlc\codegen\schema.py", line 562, in handle_command
    gen.write()
  File "c:\users\rv\.virtualenvs\lms-proj\lib\site-packages\sgqlc\codegen\schema.py", line 114, in write
    self.write_types()
  File "c:\users\rv\.virtualenvs\lms-proj\lib\site-packages\sgqlc\codegen\schema.py", line 215, in write_types
    mapped(t)
  File "c:\users\rv\.virtualenvs\lms-proj\lib\site-packages\sgqlc\codegen\schema.py", line 386, in write_type_object
    self.write_type_container(t, bases, own_fields, write_field)
  File "c:\users\rv\.virtualenvs\lms-proj\lib\site-packages\sgqlc\codegen\schema.py", line 337, in write_type_container
    write_field(field, siblings)
  File "c:\users\rv\.virtualenvs\lms-proj\lib\site-packages\sgqlc\codegen\schema.py", line 318, in write_field_output
    self.write_arg(a, siblings)
  File "c:\users\rv\.virtualenvs\lms-proj\lib\site-packages\sgqlc\codegen\schema.py", line 292, in write_arg
    defval = repr(parse_graphql_value_to_json(defval))
  File "c:\users\rv\.virtualenvs\lms-proj\lib\site-packages\sgqlc\codegen\schema.py", line 66, in parse_graphql_value_to_json
    v = v.value
AttributeError: 'NullValueNode' object has no attribute 'value'
`

**Comment by barbieri** [comment]
could you try with git `master` branch? The line 66 of `codegen/schema.py` is not that anymore, so maybe it was fixed, in particular 8ff6d9c5cf7129b141d2ea1ad0c2ea27e5627e27 that fixes #119 should have fixed it.

I need to prepare a new release, but I still have many open issues to work on, maybe I'll this weekend.

**Comment by rveeravalli** [comment]
I was using the latest release via pip install. Syncing it with master fixed the error, thank you very much.
