### ISSUE TITLE
Failing on sgqlc.types.Enum without values

### ISSUE THREAD

**Issue by ascheucher** [profusion/sgqlc#156]
Hi barbieri,
using the latest version of the Shopify API, I realised the type system is failing on an empty sgqlc.types.Enum generated out of [a deprecated Shopify type](https://shopify.dev/docs/admin-api/graphql/reference/discounts-and-marketing/kitskilllocale).

Last working Shopify schema 2020_10:
```
class KitSkillLocale(sgqlc.types.Enum):
    __schema__ = schema
    __choices__ = ('EN',)
```

First not working Shopify schema 2021_01:
```
class KitSkillLocale(sgqlc.types.Enum):
    __schema__ = schema
    __choices__ = ()       # <-- no values here.
```

I assume that's against the GraphQL standards, but sadly Shopify doesn't care too much.

Generation of the schema.py file worked like a charm, but importing it failed:

Code:
```
import logging
import yaml
import sgqlc
import sgqlc.types
import sgqlc.operation
from sgqlc.endpoint.http import HTTPEndpoint
from otaya.shopify.sgql_client import SyGqlClient, SyGraphQlInternalError
import otaya.shopify.sgql.v2021_04.schema as schema

_schema = schema
_schema_root = _schema.schema

.... 
```

Traceback:
```
vscode ➜ /workspace (develop ✗) $  cd /workspace ; /usr/bin/env /usr/local/bin/python /home/vscode/.vscode-server/extensions/ms-python.python-2021.5.842923320/pythonFiles/lib/python/debugpy/launcher 36593 -- /workspace/tinker_around/sgqlc_list_test.py 
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/vscode/.vscode-server/extensions/ms-python.python-2021.5.842923320/pythonFiles/lib/python/debugpy/__main__.py", line 45, in <module>
    cli.main()
  File "/home/vscode/.vscode-server/extensions/ms-python.python-2021.5.842923320/pythonFiles/lib/python/debugpy/../debugpy/server/cli.py", line 444, in main
    run()
  File "/home/vscode/.vscode-server/extensions/ms-python.python-2021.5.842923320/pythonFiles/lib/python/debugpy/../debugpy/server/cli.py", line 285, in run_file
    runpy.run_path(target_as_str, run_name=compat.force_str("__main__"))
  File "/usr/local/lib/python3.9/runpy.py", line 268, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/usr/local/lib/python3.9/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/usr/local/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/workspace/tinker_around/sgqlc_list_test.py", line 8, in <module>
    import otaya.shopify.sgql.v2021_04.schema as schema
  File "/workspace/design_db/modules/otaya/shopify/sgql/v2021_04/schema.py", line 405, in <module>
    class KitSkillLocale(sgqlc.types.Enum):
  File "/home/vscode/.local/lib/python3.9/site-packages/sgqlc/types/__init__.py", line 1316, in __init__
    raise ValueError(name + ': missing __choices__')
ValueError: KitSkillLocale: missing __choices__
vscode ➜ /workspace (develop ✗) $ 
```

For now I just have commented out the KitSkillLocale class. But should this be supported by the sgqlc type system maybe?
I am not deep enough into the GraphQL definitions to judge this. Just thought I report it in case it should be supported.

**Comment by barbieri** [comment]
I can change it to check only for missing property (None), allowing an empty tuple... is that ok?

**Comment by barbieri** [comment]
should fix this issue, otherwise reopen
