### ISSUE TITLE
operation codegen fails with 'Document' is not iterable

### ISSUE THREAD

**Issue by worrel** [profusion/sgqlc#169]
I'm using 14.1 codegen to build queries off a Hasura schema.

I've successfully generated a schema.py from the introspected JSON, but the `operation` command isn't working for me (even with very simplified queries).

`sgqlc-codegen operation sgqlc_schema sgqlc_operations.py test.gql` (note I've also tried adding `--schema schema.json` to this as in the docs but the error is the same):

````
Traceback (most recent call last):
  File "/Users/rory/code/github/Cogitai/sai/.venv/bin/sgqlc-codegen", line 8, in <module>
    sys.exit(main())
  File "/Users/rory/code/github/Cogitai/sai/.venv/lib/python3.9/site-packages/sgqlc/codegen/__init__.py", line 130, in main
    args.func(args)
  File "/Users/rory/code/github/Cogitai/sai/.venv/lib/python3.9/site-packages/sgqlc/codegen/operation.py", line 934, in handle_command
    gen.write()
  File "/Users/rory/code/github/Cogitai/sai/.venv/lib/python3.9/site-packages/sgqlc/codegen/operation.py", line 811, in write
    self.write_operations()
  File "/Users/rory/code/github/Cogitai/sai/.venv/lib/python3.9/site-packages/sgqlc/codegen/operation.py", line 831, in write_operations
    self.write_operation(source)
  File "/Users/rory/code/github/Cogitai/sai/.venv/lib/python3.9/site-packages/sgqlc/codegen/operation.py", line 841, in write_operation
    for kind, name, code in visit(gql, visitor):
TypeError: 'Document' object is not iterable
````

my GQL file is very simple: 
````
query RunsActive {
    runs {
    id
    created_at
  }
}
````

My schema is substantially larger & I can't publish it here.  I did hack `operation.py` to output what `visit(gql, visitor)` on line 841 was returning:
````
Document(definitions=[OperationDefinition(operation='query', name=Name(value='RunsActive'), variable_definitions=[], directives=[], selection_set=SelectionSet(selections=[Field(alias=None, name=Name(value='runs'), arguments=[], directives=[], selection_set=SelectionSet(selections=[Field(alias=None, name=Name(value='id'), arguments=[], directives=[], selection_set=None), Field(alias=None, name=Name(value='created_at'), arguments=[], directives=[], selection_set=None)]))]))])````

**Comment by barbieri** [comment]
I'll take a look, it may be a breaking change with `graphql-core` dependency. Could you check which version are you using? In the `Pipfile.lock` there is the version we test against, currently `3.1.5`
