### ISSUE TITLE
operation codegen failing on boolean literals

### ISSUE THREAD

**Issue by worrel** [profusion/sgqlc#170]
The first query (boolean literal) fails to generate with `ValueError: not enough values to unpack (expected 3, got 1)` while the second form succeeds:

FAILS:
```
query MyQuery {
   things(where: { global: { _eq: true } }) {
      id
   }
}
```

SUCCEEDS
```
query MyQuery($global: Boolean!) {
   things(where: { global: { _eq: $global } }) {
      id
   }
}
```

Full traceback:
````
Traceback (most recent call last):
  File "/Users/rory/code/github/Cogitai/sai/.venv/bin/sgqlc-codegen", line 8, in <module>
    sys.exit(main())
  File "/Users/rory/code/github/Cogitai/sai/.venv/lib/python3.9/site-packages/sgqlc/codegen/__init__.py", line 130, in main
    args.func(args)
  File "/Users/rory/code/github/Cogitai/sai/.venv/lib/python3.9/site-packages/sgqlc/codegen/operation.py", line 934, in handle_command
    gen.write()
  File "/Users/rory/code/github/Cogitai/sai/.venv/lib/python3.9/site-packages/sgqlc/codegen/operation.py", line 811, in write
    self.write_operations()
  File "/Users/rory/code/github/Cogitai/sai/.venv/lib/python3.9/site-packages/sgqlc/codegen/operation.py", line 831, in write_operations
    self.write_operation(source)
  File "/Users/rory/code/github/Cogitai/sai/.venv/lib/python3.9/site-packages/sgqlc/codegen/operation.py", line 841, in write_operation
    for kind, name, code in thing:
ValueError: not enough values to unpack (expected 3, got 1)
````

**Comment by barbieri** [comment]
could you confirm the `graphql-core` version you're using?

**Comment by worrel** [comment]
I'm on 3.1.5 (also happens on 3.1.6)

**Comment by barbieri** [comment]
ok, I'll take a look, but kinda overloaded at work nowadays. If you could reproduce that with the existing examples, it would help me a lot, ex https://github.com/profusion/sgqlc/tree/master/examples/github

very likely it's in the return of the `leave_*` methods of `GraphQLToPython`.

This specific trace is https://github.com/profusion/sgqlc/blob/master/sgqlc/codegen/operation.py#L833-L841

Which should be getting the tuple returned here: https://github.com/profusion/sgqlc/blob/master/sgqlc/codegen/operation.py#L520-L527

but seems this is not the case, since it's returning a single value, not the tuple with the 3 arguments... 🤔

**Comment by worrel** [comment]
@barbieri thanks for taking a look, i'll try debug further & report back!

**Comment by J0hnG4lt** [comment]
Hi, @barbieri . I think I'm facing the same issue.

When I run this command:

``bash
sgqlc-codegen operation my_schema ./operations/dataset.py /home/georvic/repos/datahub/datahub-web-react/src/graphql/dataset.graphql
```

 with the following file: https://github.com/datahub-project/datahub/blob/master/datahub-web-react/src/graphql/dataset.graphql

I see the following output:

```console
Traceback (most recent call last):
  File "/home/georvic/anaconda3/envs/datahub/bin/sgqlc-codegen", line 8, in <module>
    sys.exit(main())
  File "/home/georvic/anaconda3/envs/datahub/lib/python3.7/site-packages/sgqlc/codegen/__init__.py", line 130, in main
    args.func(args)
  File "/home/georvic/anaconda3/envs/datahub/lib/python3.7/site-packages/sgqlc/codegen/operation.py", line 949, in handle_command
    gen.write()
  File "/home/georvic/anaconda3/envs/datahub/lib/python3.7/site-packages/sgqlc/codegen/operation.py", line 826, in write
    self.write_operations()
  File "/home/georvic/anaconda3/envs/datahub/lib/python3.7/site-packages/sgqlc/codegen/operation.py", line 846, in write_operations
    self.write_operation(source)
  File "/home/georvic/anaconda3/envs/datahub/lib/python3.7/site-packages/sgqlc/codegen/operation.py", line 856, in write_operation
    for kind, name, code in visit(gql, visitor):
ValueError: not enough values to unpack (expected 3, got 1)
```

When taking a look in the dataset.graphql file, I can see the following: https://github.com/datahub-project/datahub/blob/master/datahub-web-react/src/graphql/dataset.graphql#L114

```graphql
    autoRenderAspects: aspects(input: { autoRenderOnly: true }) {
        aspectName
        payload
        renderSpec {
            displayType
            displayName
            key
        }
    }
```

So, it seems the same issue.

My versions are:

sgqlc==16.2
Python 3.7.16

**Comment by J0hnG4lt** [comment]
Hi, @barbieri . I think I'm facing the same issue.

When I run this command:

```bash
sgqlc-codegen operation my_schema ./operations/dataset.py /home/georvic/repos/datahub/datahub-web-react/src/graphql/dataset.graphql
```

 with the following file: https://github.com/datahub-project/datahub/blob/master/datahub-web-react/src/graphql/dataset.graphql

I see the following output:

```console
Traceback (most recent call last):
  File "/home/georvic/anaconda3/envs/datahub/bin/sgqlc-codegen", line 8, in <module>
    sys.exit(main())
  File "/home/georvic/anaconda3/envs/datahub/lib/python3.7/site-packages/sgqlc/codegen/__init__.py", line 130, in main
    args.func(args)
  File "/home/georvic/anaconda3/envs/datahub/lib/python3.7/site-packages/sgqlc/codegen/operation.py", line 949, in handle_command
    gen.write()
  File "/home/georvic/anaconda3/envs/datahub/lib/python3.7/site-packages/sgqlc/codegen/operation.py", line 826, in write
    self.write_operations()
  File "/home/georvic/anaconda3/envs/datahub/lib/python3.7/site-packages/sgqlc/codegen/operation.py", line 846, in write_operations
    self.write_operation(source)
  File "/home/georvic/anaconda3/envs/datahub/lib/python3.7/site-packages/sgqlc/codegen/operation.py", line 856, in write_operation
    for kind, name, code in visit(gql, visitor):
ValueError: not enough values to unpack (expected 3, got 1)
```

When taking a look in the dataset.graphql file, I can see the following: https://github.com/datahub-project/datahub/blob/master/datahub-web-react/src/graphql/dataset.graphql#L114

```graphql
    autoRenderAspects: aspects(input: { autoRenderOnly: true }) {
        aspectName
        payload
        renderSpec {
            displayType
            displayName
            key
        }
    }
```

So, it seems the same issue.

My versions are:

sgqlc==16.2
Python 3.7.16

**Comment by barbieri** [comment]
hi, could you check with `graphql-core==3.2.3`? I bet the error is there, if that's the case I'll need to check how to make a code that works in both or just bump the minimum requirement to be that version (since it's out since september 2022, almost one year old).

**Comment by barbieri** [comment]
sorry, edited the last msg, it's 3.1.6 that should be tested.

**Comment by barbieri** [comment]
Looking at https://github.com/datahub-project/datahub/blob/master/datahub-web-react/src/graphql/dataset.graphql#L114 what calls attention is the usage of an alias (`autoRenderAspects`), we should be handling them correctly at https://github.com/profusion/sgqlc/blob/master/sgqlc/codegen/operation.py#L651-L671 

```py
        alias = ''
        if node.alias:
            alias = to_python_name(node.alias)
            args = list(args) + [('__alias__', alias)]
```

could you please check this part? Also, if you can print the `kind` at https://github.com/graphql-python/graphql-core/blob/main/src/graphql/language/visitor.py#L145-L153, we could see if there is something we're missing.

**Comment by J0hnG4lt** [comment]
Hi, @barbieri . Thanks for taking a look. Yes, it also happens with that version:

![imagen](https://github.com/profusion/sgqlc/assets/10814689/1be5eac6-a85a-4ffc-a8dd-1809c1cb0386)

**Comment by J0hnG4lt** [comment]
If I use the version I tested originally, I do find the function. After placing a print call, I get the following:
![imagen](https://github.com/profusion/sgqlc/assets/10814689/95b45248-4fa1-4676-b888-8f962f3d1bc2)

So, the last element before the exception is: boolean_value
