### ISSUE TITLE
if data and data.get('errors'): -> AttributeError: 'str' object has no attribute 'get' / Also: Catching 500 server errors

### ISSUE THREAD

**Issue by metachris** [profusion/sgqlc#24]
If the `HTTPEndpoint` encounters a 500 error, it leads to the following traceback:

    http://api.staging.nash.io/api/graphql: HTTP Error 500: Internal Server Error
    Traceback (most recent call last):
    File "...lib/python3.7/site-packages/sgqlc/endpoint/http.py", line 183, in __call__
        with self.urlopen(req, timeout=timeout or self.timeout) as f:
    File ".../lib/python3.7/urllib/request.py", line 222, in urlopen
        return opener.open(url, data, timeout)
    File ".../lib/python3.7/urllib/request.py", line 531, in open
        response = meth(req, response)
    File ".../lib/python3.7/urllib/request.py", line 641, in http_response
        'http', request, response, code, msg, hdrs)
    File ".../lib/python3.7/urllib/request.py", line 569, in error
        return self._call_chain(*args)
    File ".../lib/python3.7/urllib/request.py", line 503, in _call_chain
        result = func(*args)
    File ".../lib/python3.7/urllib/request.py", line 649, in http_error_default
        raise HTTPError(req.full_url, code, msg, hdrs, fp)
    urllib.error.HTTPError: HTTP Error 500: Internal Server Error

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
    File "test-gql.py", line 54, in <module>
        data = gql_endpoint(op)
    File "...lib/python3.7/site-packages/sgqlc/endpoint/http.py", line 193, in __call__
        return self._log_http_error(query, req, exc)
    File "...lib/python3.7/site-packages/sgqlc/endpoint/http.py", line 254, in _log_http_error
        if data and data.get('errors'):
    AttributeError: 'str' object has no attribute 'get'
    
(`gql_endpoint` is a simple `HTTPEndpoint`)

Also, ideally we'd be able to catch the original HTTPError.

**Comment by metachris** [comment]
The issue is if the response is "Internal server error" then `data` will be a string rather than an object:

https://github.com/profusion/sgqlc/blob/master/sgqlc/endpoint/http.py#L253

**Comment by barbieri** [comment]
thanks, i need to handle the case where the data itself wasn't converted to json (dict)

**Comment by metachris** [comment]
The PR that fixes it imo would be #25.

**Comment by barbieri** [comment]
although this specific fix would be a single line, I did some changes to make the error reporting more robust, taking object that do not conform to the GraphQL error formats as well.

Now the returned object also contain `exception`, `status` and `headers` in case of HTTP failures.

**Comment by metachris** [comment]
awesome!

**Comment by metachris** [comment]
Can you make a minor release sometime soon with this fix? Would be great to have that! Thanks :) 👍

**Comment by barbieri** [comment]
will do this weekend!

**Comment by barbieri** [comment]
v7 is out

**Comment by metachris** [comment]
Great, thanks so much for the heads-up!
