### ISSUE TITLE
ImportError in /types/__init__.py

### ISSUE THREAD

**Issue by SShatun** [profusion/sgqlc#30]
Hi! It is maybe stupid issue but I am getting this error after updating master brunch today:
```Error processing line 1 of /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/protobuf-3.6.1-py3.7-nspkg.pth:

Fatal Python error: initsite: Failed to import the site module
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site.py", line 168, in addpackage
    exec(line)
  File "<string>", line 1, in <module>
  File "/Users/homedir/sgqlc/types/__init__.py", line 510, in <module>
    import json
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/__init__.py", line 106, in <module>
    from .decoder import JSONDecoder, JSONDecodeError
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/decoder.py", line 3, in <module>
    import re
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/re.py", line 122, in <module>
    import enum
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/enum.py", line 2, in <module>
    from types import MappingProxyType, DynamicClassAttribute
ImportError: cannot import name 'MappingProxyType' from 'types' (/Users/homedir/sgqlc/types/__init__.py)
```
However importing `json` package in other script works well:
```
import json

print(json)

/usr/local/bin/python3.7 /Users/homedir/sandbox/ttt.py
<module 'json' from '/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/__init__.py'>
```

**Comment by barbieri** [comment]
weird, this is unrelated to the changes I did. Are you exporting `$PYTHONPATH` or something like that? It seems `types` is being used from `sgqlc/types` instead of the python stdlib...

**Comment by SShatun** [comment]
Eah, I think it is my problem
