### ISSUE TITLE
AttributeError: module 're' has no attribute 'compile'

### ISSUE THREAD

**Issue by petrus-jvrensburg** [profusion/sgqlc#50]
When trying to run basic examples from a virtualenv, I get this error caused by the local `types.py` module taking precedent over python's builtin types module.

```
(env) PJs-MacBook-Pro-2:examples petrus$ python basic/http-endpoint.py 
Traceback (most recent call last):
  File "basic/http-endpoint.py", line 4, in <module>
    import json
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/__init__.py", line 106, in <module>
    from .decoder import JSONDecoder, JSONDecodeError
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/decoder.py", line 3, in <module>
    import re
  File "/Users/petrus/code/sgqlc/examples/env/lib/python3.7/re.py", line 122, in <module>
    import enum
  File "/Users/petrus/code/sgqlc/examples/env/lib/python3.7/enum.py", line 2, in <module>
    from types import MappingProxyType, DynamicClassAttribute
  File "/Users/petrus/code/sgqlc/examples/basic/types.py", line 4, in <module>
    from sgqlc.endpoint.http import HTTPEndpoint
  File "/Users/petrus/code/sgqlc/examples/env/lib/python3.7/site-packages/sgqlc/endpoint/http.py", line 25, in <module>
    import logging
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 26, in <module>
    import sys, os, time, io, traceback, warnings, weakref, collections.abc
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/traceback.py", line 5, in <module>
    import linecache
  File "/Users/petrus/code/sgqlc/examples/env/lib/python3.7/linecache.py", line 11, in <module>
    import tokenize
  File "/Users/petrus/code/sgqlc/examples/env/lib/python3.7/tokenize.py", line 37, in <module>
    cookie_re = re.compile(r'^[ \t\f]*#.*?coding[:=][ \t]*([-\w.]+)', re.ASCII)
AttributeError: module 're' has no attribute 'compile'
```

**Comment by barbieri** [comment]
yeah, this is because you're not running from inside the samples folder. The PR #51 should help to avoid that clash.
