### ISSUE TITLE
Cannot use Variable to stand for complex-typed argument

### ISSUE THREAD

**Issue by grantwwu** [profusion/sgqlc#64]
```# flake8: noqa

import sgqlc.types

from sgqlc.operation import Operation

repro_schema = sgqlc.types.Schema()

Boolean = sgqlc.types.Boolean

ID = sgqlc.types.ID

String = sgqlc.types.String

Variable = sgqlc.types.Variable

class IngestDataFromS3Input(sgqlc.types.Input):
    __schema__ = repro_schema
    src = sgqlc.types.Field(sgqlc.types.non_null(String), graphql_name='src')
    dest = sgqlc.types.Field(String, graphql_name='dest')
    recursive = sgqlc.types.Field(Boolean, graphql_name='recursive')

class IngestDataFromS3Payload(sgqlc.types.Type):
    __schema__ = repro_schema
    ingestion_job_id = sgqlc.types.Field(ID, graphql_name='ingestionJobID')

class Mutation(sgqlc.types.Type):
    __schema__ = repro_schema
    ingest_data_from_s3 = sgqlc.types.Field(IngestDataFromS3Payload, graphql_name='ingestDataFromS3', args=sgqlc.types.ArgDict((
        ('input', sgqlc.types.Arg(sgqlc.types.non_null(IngestDataFromS3Input), graphql_name='input', default=None)),
))
    )
    ingest_data_from_s3_fixed = sgqlc.types.Field(IngestDataFromS3Payload, graphql_name='ingestDataFromS3Fixed', args=sgqlc.types.ArgDict((
        ('input', sgqlc.types.Arg(String, graphql_name='input', default=None)),
))
    )

op = Operation(repro_schema.Mutation, name="ingest_from_s3_fixed", input=str)
ingestDataFromS3Fixed = op.ingest_data_from_s3_fixed(input=Variable("input"))
ingestDataFromS3Fixed.ingestion_job_id()
print(str(op))

op = Operation(repro_schema.Mutation, name="ingest_from_s3", input=IngestDataFromS3Input)
ingestDataFromS3 = op.ingest_data_from_s3(input=Variable("input"))
ingestDataFromS3.ingestion_job_id()
print(str(op))
```

SGQLC appears to be trying to get the fields of the Input type, if that makes sense:

```
Traceback (most recent call last):
  File "repro.py", line 46, in <module>
    print(str(op))
  File "/Users/grant.wu/petuum/petctl_venv/lib/python3.7/site-packages/sgqlc/operation/__init__.py", line 1822, in __str__
    return self.__to_graphql__()
  File "/Users/grant.wu/petuum/petctl_venv/lib/python3.7/site-packages/sgqlc/operation/__init__.py", line 1803, in __to_graphql__
    indent, indent_string, auto_select_depth)
  File "/Users/grant.wu/petuum/petctl_venv/lib/python3.7/site-packages/sgqlc/operation/__init__.py", line 1529, in __to_graphql__
    next_indent, indent_string, auto_select_depth,
  File "/Users/grant.wu/petuum/petctl_venv/lib/python3.7/site-packages/sgqlc/operation/__init__.py", line 1241, in __to_graphql__
    self.__args__, indent, indent_string)
  File "/Users/grant.wu/petuum/petctl_venv/lib/python3.7/site-packages/sgqlc/types/__init__.py", line 2233, in __to_graphql_input__
    args.append(p.__to_graphql_input__(v))
  File "/Users/grant.wu/petuum/petctl_venv/lib/python3.7/site-packages/sgqlc/types/__init__.py", line 2075, in __to_graphql_input__
    v = self.type.__to_graphql_input__(value, indent, indent_string)
  File "/Users/grant.wu/petuum/petctl_venv/lib/python3.7/site-packages/sgqlc/types/__init__.py", line 896, in __to_graphql_input__
    return t.__to_graphql_input__(value, indent, indent_string)
  File "/Users/grant.wu/petuum/petctl_venv/lib/python3.7/site-packages/sgqlc/types/__init__.py", line 2453, in __to_graphql_input__
    v = value[f.graphql_name]
TypeError: 'Variable' object is not subscriptable
```

Note that when the argument is not a custom type, it works as expected (see https://sgqlc.readthedocs.io/en/latest/sgqlc.operation.html, CTRL-F "Operations can have arugments)

**Comment by barbieri** [comment]
I'll look into this, likely missing a check if the whole input object is a variable.

**Comment by johnjstuart** [comment]
Any updates on this? If you're low on bandwidth and it's something I could help out with I'd be happy to pitch in.

**Comment by barbieri** [comment]
yeah, I was out during the past week and this week is being super busy. If you can investigate, in search how I handle the `Variable` cases in other places using `isinstance()` ([example](https://github.com/profusion/sgqlc/blob/master/sgqlc/types/__init__.py#L2064)). It's a matter of finding the correct spot to introduce this check, when it's a variable we just encode that variable directly, so the generated query is `$variable`.

If you manage to solve it, remember to run the tests (there are git hooks at `utils/git`) and add a doctest to get it covered.

**Comment by johnjstuart** [comment]
@barbieri Now that the fix is in I'm able to start developing again, but can I ask when the next planned release of SGQLC will be?

**Comment by barbieri** [comment]
I'll be out during the weekend, can do it on Monday, if not ping me again.

**Comment by johnjstuart** [comment]
@barbieri Bump.

**Comment by barbieri** [comment]
sorry taking so long, busy times here.

See:
 - https://pypi.org/project/sgqlc/8.1/
 - https://github.com/profusion/sgqlc/releases/tag/v8.1

This is the first release fully contributed by the community :-)

**Comment by johnjstuart** [comment]
Nice, Glad to have be a contributor!
